# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='pet_name',
            new_name='pet_nameasdfasdfas',
        ),
    ]
