# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0002_auto_20171024_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='pet_nameasdfasdfas',
            new_name='pet_name',
        ),
        migrations.AlterField(
            model_name='pet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets_ownedaasdfasdf', to='login_app.User'),
        ),
    ]
